=== adobe/spectrum-css/schemas/metadata.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "JSON schema for Spectrum CSS component metadata",
	"type": "object",
	"version": "1",
	"description": "A validation schema for the Spectrum CSS component metadata.",
	"properties": {
		"sourceFile": {
			"type": "string",
			"pattern": "^.+\\.css$",
			"description": "The path to the source file used in generating the metadata."
		},
		"selectors": {
			"description": "These are the selectors available for the component.",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"modifiers": {
			"description": "These are the modifiers available for the component.",
			"type": "object",
			"patternProperties": {
				"^mod-": {
					"$ref": "#/definitions/argType"
				}
			}
		},
		"component": {
			"description": "The component-level custom properties for the component.",
			"type": "object",
			"patternProperties": {
				"^spectrum-": {
					"$ref": "#/definitions/argType"
				}
			}
		},
		"global": {
			"description": "The global custom properties used in this component as generated by the design tokens.",
			"type": "object",
			"patternProperties": {
				"^spectrum-": {
					"$ref": "#/definitions/argType"
				}
			}
		},
		"system-theme": {
			"description": "The system theme hooks created by the postcss tooling to allow theme toggling on a component.",
			"type": "object",
			"patternProperties": {
				"^system-": {
					"$ref": "#/definitions/argType"
				}
			}
		},
		"passthroughs": {
			"description": "Modifier custom properties for nested components that are passed through by this component.",
			"type": "object",
			"patternProperties": {
				"^mod-": {
					"$ref": "#/definitions/argType"
				}
			}
		},
		"high-contrast": {
			"description": "Custom properties that allow high-contrast styles to be applied to the component.",
			"type": "object",
			"patternProperties": {
				"^highcontrast-": {
					"$ref": "#/definitions/argType"
				}
			}
		}
	},
	"required": [
		"sourceFile",
		"selectors",
		"modifiers",
		"component",
		"global",
		"system-theme",
		"passthroughs",
		"high-contrast"
	],
	"additionalProperties": false,
	"definitions": {
		"argType": {
			"type": "object",
			"properties": {
				"description": {
					"type": "string"
				},
				"control": {
					"$ref": "#/definitions/control"
				},
				"category": {
					"type": "string"
				},
				"subcategory": {
					"type": "string"
				},
				"value": {
					"type": "string"
				},
				"if": {
					"type": "object",
					"allOf": [
						{
							"oneOf": [
								{
									"properties": {
										"arg": {
											"type": "string"
										}
									},
									"required": ["arg"]
								},
								{
									"properties": {
										"global": {
											"type": "string"
										}
									},
									"required": ["global"]
								}
							]
						},
						{
							"oneOf": [
								{
									"properties": {
										"truthy": {
											"type": "boolean"
										}
									}
								},
								{
									"properties": {
										"exists": {
											"type": "boolean"
										}
									},
									"required": ["exists"]
								},
								{
									"properties": {
										"eq": {
											"type": "string"
										}
									},
									"required": ["eq"]
								},
								{
									"properties": {
										"neq": {
											"type": "string"
										}
									},
									"required": ["neq"]
								}
							]
						}
					]
				},
				"mapping": {
					"type": "object"
				},
				"name": {
					"type": "string"
				},
				"options": {
					"type": "array",
					"readonly": true
				},
				"table": {
					"type": "object",
					"properties": {
						"category": {
							"type": "string"
						},
						"subcategory": {
							"type": "string"
						},
						"defaultValue": {
							"type": "object",
							"properties": {
								"summary": {
									"type": "string"
								},
								"detail": {
									"type": "string"
								}
							}
						},
						"disable": {
							"type": "boolean"
						},
						"type": {
							"type": "object",
							"properties": {
								"summary": {
									"type": "string"
								},
								"detail": {
									"type": "string"
								}
							}
						}
					},
					"additionalProperties": true
				},
				"type": {}
			},
			"additionalProperties": false
		},
		"control": {
			"oneOf": [
				{
					"$ref": "#/definitions/controlTypes"
				},
				{
					"type": "boolean",
					"enum": [false]
				},
				{
					"type": "object",
					"properties": {
						"type": {
							"$ref": "#/definitions/controlTypes"
						},
						"disable": {
							"type": "boolean"
						}
					},
					"required": ["type"],
					"allOf": [
						{
							"if": {
								"properties": {
									"type": { "const": "color" }
								},
								"then": {
									"properties": {
										"presetColors": { "type": "array", "items": { "type": "string" } }
									}
								}
							}
						},
						{
							"if": {
								"properties": {
									"type": { "const": "file" }
								},
								"then": {
									"properties": {
										"accept": { "type": "string" }
									}
								}
							}
						},
						{
							"if": {
								"properties": {
									"type": { "anyOf": [ { "const": "inline-check" }, { "const": "radio" }, { "const": "inline-radio" }, { "const": "select" }, { "const": "multi-select" } ] }
								},
								"then": {
									"properties": {
										"labels": { "type": "object", "patternProperties": { "^.*$": { "type": "string" } } }
									}
								}
							}
						},
						{
							"if": {
								"properties": {
									"type": { "anyOf": [ { "const": "range" }, { "const": "number" } ] }
								},
								"then": {
									"properties": {
										"max": { "type": "number" },
										"min": { "type": "number" },
										"step": { "type": "number" }
									}
								}
							}
						}
					]
				}
			]
		},
		"controlTypes": {
			"type": "string",
			"enum": ["color", "date", "boolean", "number", "text", "object", "check", "inline-check", "radio", "inline-radio", "select", "multi-select", "file", "range"]
		}
	}
}

=== adobe/spectrum-css/components/asset/dist/metadata.json
{
  "sourceFile": "index.css",
  "selectors": [
    ".spectrum-Asset",
    ".spectrum-Asset-file",
    ".spectrum-Asset-fileBackground",
    ".spectrum-Asset-fileOutline",
    ".spectrum-Asset-folder",
    ".spectrum-Asset-folderBackground",
    ".spectrum-Asset-folderOutline",
    ".spectrum-Asset-image"
  ],
  "modifiers": {
    "mod-asset-folder-background-color": {
      "description": "Used by `--spectrum-asset-folder-background`. Defaults to `var(--spectrum-asset-folder-background-color)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-asset-file-background-color": {
      "description": "Used by `--spectrum-asset-file-background`. Defaults to `var(--spectrum-asset-file-background-color)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-asset-icon-outline-color": {
      "description": "Used by `--spectrum-asset-folder-outline`, `--spectrum-asset-file-outline`. Defaults to `var(--spectrum-asset-icon-outline-color)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-asset-icon-min-width": {
      "description": "Used by `.spectrum-Asset-file, .spectrum-Asset-folder`.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-asset-icon-max-width": {
      "description": "Used by `.spectrum-Asset-file, .spectrum-Asset-folder`.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-asset-icon-margin": {
      "description": "Used by `.spectrum-Asset-file, .spectrum-Asset-folder`.",
      "control": "text",
      "category": "Modifier"
    }
  },
  "component": {
    "spectrum-asset-folder-background": {
      "value": "var(--highcontrast-asset-icon-background-color, var(--mod-asset-folder-background-color, var(--spectrum-asset-folder-background-color)))",
      "description": "Defined in `.spectrum-Asset`. Used by `.spectrum-Asset-folderBackground`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-asset-folder-background-color": {
      "value": "var(--system-asset-folder-background-color)",
      "description": "Defined in `.spectrum-Asset`. Used by `--spectrum-asset-folder-background`.",
      "control": "color",
      "category": "Component"
    },
    "spectrum-asset-file-background": {
      "value": "var(--highcontrast-asset-icon-background-color, var(--mod-asset-file-background-color, var(--spectrum-asset-file-background-color)))",
      "description": "Defined in `.spectrum-Asset`. Used by `.spectrum-Asset-fileBackground`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-asset-file-background-color": {
      "value": "var(--system-asset-file-background-color)",
      "description": "Defined in `.spectrum-Asset`. Used by `--spectrum-asset-file-background`.",
      "control": "color",
      "category": "Component"
    },
    "spectrum-asset-folder-outline": {
      "value": "var(--mod-asset-icon-outline-color, var(--spectrum-asset-icon-outline-color))",
      "description": "Defined in `.spectrum-Asset`. Used by `.spectrum-Asset-folderOutline`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-asset-icon-outline-color": {
      "value": "var(--system-asset-icon-outline-color)",
      "description": "Defined in `.spectrum-Asset`. Used by `--spectrum-asset-folder-outline`, `--spectrum-asset-file-outline`.",
      "control": "color",
      "category": "Component"
    },
    "spectrum-asset-file-outline": {
      "value": "var(--mod-asset-icon-outline-color, var(--spectrum-asset-icon-outline-color))",
      "description": "Defined in `.spectrum-Asset`. Used by `.spectrum-Asset-fileOutline`.",
      "control": "text",
      "category": "Component"
    }
  },
  "global": {
    "spectrum-gray-200": {
      "description": "Used by `--system-asset-folder-background-color`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-gray-25": {
      "description": "Used by `--system-asset-file-background-color`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-gray-500": {
      "description": "Used by `--system-asset-icon-outline-color`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-animation-duration-100": {
      "description": "Used by `.spectrum-Asset-image`.",
      "control": "text",
      "category": "Global"
    }
  },
  "system-theme": {
    "system-asset-folder-background-color": {
      "value": "var(--spectrum-gray-200)",
      "description": "Defined in `.spectrum`. Used by `--spectrum-asset-folder-background-color`.",
      "control": "color"
    },
    "system-asset-file-background-color": {
      "value": "var(--spectrum-gray-25)",
      "description": "Defined in `.spectrum`. Used by `--spectrum-asset-file-background-color`.",
      "control": "color"
    },
    "system-asset-icon-outline-color": {
      "value": "var(--spectrum-gray-500)",
      "description": "Defined in `.spectrum`. Used by `--spectrum-asset-icon-outline-color`.",
      "control": "color"
    }
  },
  "passthroughs": {},
  "high-contrast": {
    "highcontrast-asset-icon-background-color": {
      "value": "currentColor",
      "description": "Defined in `.spectrum-Asset`. Used by `--spectrum-asset-folder-background`, `--spectrum-asset-file-background`. Defaults to `var(--mod-asset-file-background-color, var(--spectrum-asset-file-background-color))`, if not set.",
      "control": "color"
    }
  }
}

=== adobe/spectrum-css/components/fieldgroup/dist/metadata.json
{
  "sourceFile": "index.css",
  "selectors": [
    ".spectrum-FieldGroup",
    ".spectrum-FieldGroup--horizontal .spectrum-FieldGroupInputLayout",
    ".spectrum-FieldGroup--horizontal .spectrum-FieldGroupInputLayout .spectrum-FieldGroup-item:not(:last-child)",
    ".spectrum-FieldGroup--horizontal .spectrum-FieldGroupInputLayout .spectrum-HelpText",
    ".spectrum-FieldGroup--sidelabel",
    ".spectrum-FieldGroup--toplabel",
    ".spectrum-FieldGroup--vertical .spectrum-FieldGroupInputLayout",
    ".spectrum-FieldGroupInputLayout"
  ],
  "modifiers": {},
  "component": {},
  "global": {
    "spectrum-spacing-300": {
      "value": "16px",
      "description": "Used by `.spectrum-FieldGroup--horizontal .spectrum-FieldGroupInputLayout .spectrum-FieldGroup-item:not(:last-child)`.",
      "control": "text",
      "category": "Global"
    }
  },
  "system-theme": {},
  "passthroughs": {},
  "high-contrast": {}
}

=== adobe/spectrum-css/components/meter/dist/metadata.json
{
  "sourceFile": "index.css",
  "selectors": [
    ".spectrum-Meter",
    ".spectrum-Meter.is-negative",
    ".spectrum-Meter.is-notice",
    ".spectrum-Meter.is-positive",
    ".spectrum-Meter.spectrum-Meter--sizeL",
    ".spectrum-Meter.spectrum-Meter--sizeS"
  ],
  "modifiers": {
    "mod-meter-inline-size": {
      "description": "Used by `--mod-progressbar-size-default`. Defaults to `var(--spectrum-meter-default-width)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-meter-max-width": {
      "description": "Used by `--mod-progressbar-max-size`. Defaults to `var(--spectrum-meter-maximum-width)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-meter-min-width": {
      "description": "Used by `--mod-progressbar-min-size`. Defaults to `var(--spectrum-meter-minimum-width)`, if not set.",
      "control": "text",
      "category": "Modifier"
    }
  },
  "component": {
    "spectrum-meter-default-width": {
      "description": "Used by `--mod-progressbar-size-default`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-meter-maximum-width": {
      "description": "Used by `--mod-progressbar-max-size`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-meter-minimum-width": {
      "description": "Used by `--mod-progressbar-min-size`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-meter-thickness-small": {
      "description": "Used by `--mod-progressbar-thickness`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-meter-thickness-large": {
      "description": "Used by `--mod-progressbar-thickness`.",
      "control": "text",
      "category": "Component"
    }
  },
  "global": {
    "spectrum-font-size-75": {
      "description": "Used by `--mod-progressbar-font-size`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-component-top-to-text-75": {
      "description": "Used by `--mod-progressbar-spacing-top-to-text`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-font-size-100": {
      "description": "Used by `--mod-progressbar-font-size`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-component-top-to-text-200": {
      "description": "Used by `--mod-progressbar-spacing-top-to-text`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-positive-visual-color": {
      "description": "Used by `--mod-progressbar-fill-color`.",
      "control": "color",
      "category": "Global"
    },
    "spectrum-notice-visual-color": {
      "description": "Used by `--mod-progressbar-fill-color`.",
      "control": "color",
      "category": "Global"
    },
    "spectrum-negative-visual-color": {
      "description": "Used by `--mod-progressbar-fill-color`.",
      "control": "color",
      "category": "Global"
    }
  },
  "system-theme": {},
  "passthroughs": {
    "mod-progressbar-size-default": {
      "category": "Passthrough"
    },
    "mod-progressbar-max-size": {
      "category": "Passthrough"
    },
    "mod-progressbar-min-size": {
      "category": "Passthrough"
    },
    "mod-progressbar-thickness": {
      "category": "Passthrough"
    },
    "mod-progressbar-font-size": {
      "category": "Passthrough"
    },
    "mod-progressbar-spacing-top-to-text": {
      "category": "Passthrough"
    },
    "mod-progressbar-fill-color": {
      "category": "Passthrough"
    }
  },
  "high-contrast": {}
}

=== adobe/spectrum-css/components/miller/dist/metadata.json
{
  "sourceFile": "index.css",
  "selectors": [
    ".spectrum-MillerColumns",
    ".spectrum-MillerColumns-item",
    ".spectrum-MillerColumns-item:first-child"
  ],
  "modifiers": {
    "mod-millercolumns-padding": {
      "value": "8px",
      "description": "Used by `.spectrum-MillerColumns`. <br/>Defaults to `var(--spectrum-spacing-100)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-millercolumns-inline-size": {
      "description": "Used by `.spectrum-MillerColumns-item`.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-millercolumns-margin-inline-end": {
      "value": "8px",
      "description": "Used by `.spectrum-MillerColumns-item`. <br/>Defaults to `var(--spectrum-spacing-100)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-millercolumns-margin-inline-start": {
      "value": "8px",
      "description": "Used by `.spectrum-MillerColumns-item:first-child`. <br/>Defaults to `var(--spectrum-spacing-100)`, if not set.",
      "control": "text",
      "category": "Modifier"
    }
  },
  "component": {},
  "global": {
    "spectrum-spacing-100": {
      "value": "8px",
      "description": "Used by `.spectrum-MillerColumns`, `.spectrum-MillerColumns-item`, `.spectrum-MillerColumns-item:first-child`.",
      "control": "text",
      "category": "Global"
    }
  },
  "system-theme": {},
  "passthroughs": {},
  "high-contrast": {}
}

=== adobe/spectrum-css/components/link/dist/metadata.json
{
  "sourceFile": "index.css",
  "selectors": [
    ".spectrum-Link",
    ".spectrum-Link--quiet",
    ".spectrum-Link--quiet:hover",
    ".spectrum-Link--secondary",
    ".spectrum-Link--staticBlack",
    ".spectrum-Link--staticWhite",
    ".spectrum-Link:active",
    ".spectrum-Link:focus-visible",
    ".spectrum-Link:hover"
  ],
  "modifiers": {
    "mod-link-text-color": {
      "value": "var(--mod-link-text-color-black, var(--spectrum-black))",
      "description": "Defined in `.spectrum-Link--secondary`, `.spectrum-Link:active`, `.spectrum-Link:focus-visible`, `.spectrum-Link:hover`, `.spectrum-Link--staticWhite`, `.spectrum-Link--staticBlack`. Used by `.spectrum-Link`. Defaults to `var(--mod-link-text-color-primary-default, var(--spectrum-accent-content-color-default))`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-link-text-color-secondary-default": {
      "description": "Used by `--mod-link-text-color`. Defaults to `var(--spectrum-neutral-content-color-default)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-link-text-color-hover": {
      "value": "var(--mod-link-text-color-black, var(--spectrum-black))",
      "description": "Defined in `.spectrum-Link--secondary`, `.spectrum-Link--staticWhite`, `.spectrum-Link--staticBlack`. Used by `--mod-link-text-color`. Defaults to `var(--mod-link-text-color-primary-hover, var(--spectrum-accent-content-color-hover))`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-link-text-color-secondary-hover": {
      "description": "Used by `--mod-link-text-color-hover`. Defaults to `var(--spectrum-neutral-content-color-hover)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-link-text-color-active": {
      "value": "var(--mod-link-text-color-black, var(--spectrum-black))",
      "description": "Defined in `.spectrum-Link--secondary`, `.spectrum-Link--staticWhite`, `.spectrum-Link--staticBlack`. Used by `--mod-link-text-color`. Defaults to `var(--mod-link-text-color-primary-active, var(--spectrum-accent-content-color-down))`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-link-text-color-secondary-active": {
      "description": "Used by `--mod-link-text-color-active`. Defaults to `var(--spectrum-neutral-content-color-down)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-link-text-color-focus": {
      "value": "var(--mod-link-text-color-black, var(--spectrum-black))",
      "description": "Defined in `.spectrum-Link--secondary`, `.spectrum-Link--staticWhite`, `.spectrum-Link--staticBlack`. Used by `--mod-link-text-color`. Defaults to `var(--mod-link-text-color-primary-focus, var(--spectrum-accent-content-color-key-focus))`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-link-text-color-secondary-focus": {
      "description": "Used by `--mod-link-text-color-focus`. Defaults to `var(--spectrum-neutral-content-color-key-focus)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-link-animation-duration": {
      "description": "Used by `.spectrum-Link`. Defaults to `var(--spectrum-animation-duration-100)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-link-text-color-primary-default": {
      "description": "Used by `.spectrum-Link`. Defaults to `var(--spectrum-accent-content-color-default)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-link-text-color-primary-active": {
      "description": "Used by `--mod-link-text-color`. Defaults to `var(--spectrum-accent-content-color-down)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-link-text-color-primary-focus": {
      "description": "Used by `--mod-link-text-color`. Defaults to `var(--spectrum-accent-content-color-key-focus)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-link-text-color-primary-hover": {
      "description": "Used by `--mod-link-text-color`. Defaults to `var(--spectrum-accent-content-color-hover)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-link-text-color-white": {
      "description": "Used by `--mod-link-text-color`, `--mod-link-text-color-hover`, `--mod-link-text-color-active`, `--mod-link-text-color-focus`. Defaults to `var(--spectrum-white)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-link-text-color-black": {
      "description": "Used by `--mod-link-text-color`, `--mod-link-text-color-hover`, `--mod-link-text-color-active`, `--mod-link-text-color-focus`. Defaults to `var(--spectrum-black)`, if not set.",
      "control": "color",
      "category": "Modifier"
    }
  },
  "component": {},
  "global": {
    "spectrum-neutral-content-color-default": {
      "description": "Used by `--mod-link-text-color`.",
      "control": "color",
      "category": "Global"
    },
    "spectrum-neutral-content-color-hover": {
      "description": "Used by `--mod-link-text-color-hover`.",
      "control": "color",
      "category": "Global"
    },
    "spectrum-neutral-content-color-down": {
      "description": "Used by `--mod-link-text-color-active`.",
      "control": "color",
      "category": "Global"
    },
    "spectrum-neutral-content-color-key-focus": {
      "description": "Used by `--mod-link-text-color-focus`.",
      "control": "color",
      "category": "Global"
    },
    "spectrum-animation-duration-100": {
      "description": "Used by `.spectrum-Link`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-accent-content-color-default": {
      "description": "Used by `.spectrum-Link`.",
      "control": "color",
      "category": "Global"
    },
    "spectrum-accent-content-color-down": {
      "description": "Used by `--mod-link-text-color`.",
      "control": "color",
      "category": "Global"
    },
    "spectrum-accent-content-color-key-focus": {
      "description": "Used by `--mod-link-text-color`.",
      "control": "color",
      "category": "Global"
    },
    "spectrum-accent-content-color-hover": {
      "description": "Used by `--mod-link-text-color`.",
      "control": "color",
      "category": "Global"
    },
    "spectrum-white": {
      "description": "Used by `--mod-link-text-color`, `--mod-link-text-color-hover`, `--mod-link-text-color-active`, `--mod-link-text-color-focus`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-black": {
      "description": "Used by `--mod-link-text-color`, `--mod-link-text-color-hover`, `--mod-link-text-color-active`, `--mod-link-text-color-focus`.",
      "control": "text",
      "category": "Global"
    }
  },
  "system-theme": {},
  "passthroughs": {},
  "high-contrast": {
    "highcontrast-link-text-color": {
      "value": "LinkText",
      "description": "Defined in `.spectrum-Link`. Used by `.spectrum-Link`. Defaults to `var(--mod-link-text-color, var(--mod-link-text-color-primary-default, var(--spectrum-accent-content-color-default)))`, if not set.",
      "control": "color"
    }
  }
}

=== adobe/spectrum-css/components/dropindicator/dist/metadata.json
{
  "sourceFile": "index.css",
  "selectors": [
    ".spectrum-DropIndicator",
    ".spectrum-DropIndicator--horizontal",
    ".spectrum-DropIndicator--horizontal:after",
    ".spectrum-DropIndicator--horizontal:before",
    ".spectrum-DropIndicator--vertical",
    ".spectrum-DropIndicator--vertical:after",
    ".spectrum-DropIndicator--vertical:before",
    ".spectrum-DropIndicator:after",
    ".spectrum-DropIndicator:before"
  ],
  "modifiers": {
    "mod-dropindicator-border-color": {
      "description": "Used by `.spectrum-DropIndicator`. Defaults to `var(--spectrum-dropindicator-color)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-dropindicator-circle-size": {
      "description": "Used by `.spectrum-DropIndicator:after, .spectrum-DropIndicator:before`, `.spectrum-DropIndicator--horizontal`, `.spectrum-DropIndicator--horizontal:after, .spectrum-DropIndicator--horizontal:before`, `.spectrum-DropIndicator--horizontal:before`, `.spectrum-DropIndicator--horizontal:after`, `.spectrum-DropIndicator--vertical`, `.spectrum-DropIndicator--vertical:after, .spectrum-DropIndicator--vertical:before`, `.spectrum-DropIndicator--vertical:before`, `.spectrum-DropIndicator--vertical:after`. Defaults to `var(--spectrum-dropindicator-circle-size)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-dropindicator-border-size": {
      "description": "Used by `.spectrum-DropIndicator:after, .spectrum-DropIndicator:before`, `.spectrum-DropIndicator--horizontal`, `.spectrum-DropIndicator--horizontal:after, .spectrum-DropIndicator--horizontal:before`, `.spectrum-DropIndicator--vertical`, `.spectrum-DropIndicator--vertical:after, .spectrum-DropIndicator--vertical:before`. Defaults to `var(--spectrum-dropindicator-border-size)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-dropindicator-circle-color": {
      "description": "Used by `.spectrum-DropIndicator:after, .spectrum-DropIndicator:before`. Defaults to `var(--spectrum-dropindicator-color)`, if not set.",
      "control": "color",
      "category": "Modifier"
    }
  },
  "component": {
    "spectrum-dropindicator-border-size": {
      "value": "var(--spectrum-border-width-200)",
      "description": "Defined in `.spectrum-DropIndicator`. Used by `.spectrum-DropIndicator:after, .spectrum-DropIndicator:before`, `.spectrum-DropIndicator--horizontal`, `.spectrum-DropIndicator--horizontal:after, .spectrum-DropIndicator--horizontal:before`, `.spectrum-DropIndicator--vertical`, `.spectrum-DropIndicator--vertical:after, .spectrum-DropIndicator--vertical:before`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-dropindicator-circle-size": {
      "value": "12px",
      "description": "Defined in `.spectrum-DropIndicator`. Used by `.spectrum-DropIndicator:after, .spectrum-DropIndicator:before`, `.spectrum-DropIndicator--horizontal`, `.spectrum-DropIndicator--horizontal:after, .spectrum-DropIndicator--horizontal:before`, `.spectrum-DropIndicator--horizontal:before`, `.spectrum-DropIndicator--horizontal:after`, `.spectrum-DropIndicator--vertical`, `.spectrum-DropIndicator--vertical:after, .spectrum-DropIndicator--vertical:before`, `.spectrum-DropIndicator--vertical:before`, `.spectrum-DropIndicator--vertical:after`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-dropindicator-color": {
      "description": "Used by `.spectrum-DropIndicator`, `.spectrum-DropIndicator:after, .spectrum-DropIndicator:before`.",
      "control": "color",
      "category": "Component"
    }
  },
  "global": {
    "spectrum-border-width-200": {
      "description": "Used by `--spectrum-dropindicator-border-size`.",
      "control": "text",
      "category": "Global"
    }
  },
  "system-theme": {},
  "passthroughs": {},
  "high-contrast": {
    "highcontrast-dropindicator-color": {
      "value": "Highlight",
      "description": "Defined in `.spectrum-DropIndicator`. Used by `.spectrum-DropIndicator`, `.spectrum-DropIndicator:after, .spectrum-DropIndicator:before`. Defaults to `var(--mod-dropindicator-circle-color, var(--spectrum-dropindicator-color))`, if not set.",
      "control": "color"
    }
  }
}
