=== adobe/spectrum-css/schemas/metadata.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "JSON schema for Spectrum CSS component metadata",
	"type": "object",
	"version": "1",
	"description": "A validation schema for the Spectrum CSS component metadata.",
	"properties": {
		"sourceFile": {
			"type": "string",
			"pattern": "^.+\\.css$",
			"description": "The path to the source file used in generating the metadata."
		},
		"selectors": {
			"description": "These are the selectors available for the component.",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"modifiers": {
			"description": "These are the modifiers available for the component.",
			"type": "object",
			"patternProperties": {
				"^mod-": {
					"$ref": "#/definitions/argType"
				}
			}
		},
		"component": {
			"description": "The component-level custom properties for the component.",
			"type": "object",
			"patternProperties": {
				"^spectrum-": {
					"$ref": "#/definitions/argType"
				}
			}
		},
		"global": {
			"description": "The global custom properties used in this component as generated by the design tokens.",
			"type": "object",
			"patternProperties": {
				"^spectrum-": {
					"$ref": "#/definitions/argType"
				}
			}
		},
		"system-theme": {
			"description": "The system theme hooks created by the postcss tooling to allow theme toggling on a component.",
			"type": "object",
			"patternProperties": {
				"^system-": {
					"$ref": "#/definitions/argType"
				}
			}
		},
		"passthroughs": {
			"description": "Modifier custom properties for nested components that are passed through by this component.",
			"type": "object",
			"patternProperties": {
				"^mod-": {
					"$ref": "#/definitions/argType"
				}
			}
		},
		"high-contrast": {
			"description": "Custom properties that allow high-contrast styles to be applied to the component.",
			"type": "object",
			"patternProperties": {
				"^highcontrast-": {
					"$ref": "#/definitions/argType"
				}
			}
		}
	},
	"required": [
		"sourceFile",
		"selectors",
		"modifiers",
		"component",
		"global",
		"system-theme",
		"passthroughs",
		"high-contrast"
	],
	"additionalProperties": false,
	"definitions": {
		"argType": {
			"type": "object",
			"properties": {
				"description": {
					"type": "string"
				},
				"control": {
					"$ref": "#/definitions/control"
				},
				"category": {
					"type": "string"
				},
				"subcategory": {
					"type": "string"
				},
				"value": {
					"type": "string"
				},
				"if": {
					"type": "object",
					"allOf": [
						{
							"oneOf": [
								{
									"properties": {
										"arg": {
											"type": "string"
										}
									},
									"required": ["arg"]
								},
								{
									"properties": {
										"global": {
											"type": "string"
										}
									},
									"required": ["global"]
								}
							]
						},
						{
							"oneOf": [
								{
									"properties": {
										"truthy": {
											"type": "boolean"
										}
									}
								},
								{
									"properties": {
										"exists": {
											"type": "boolean"
										}
									},
									"required": ["exists"]
								},
								{
									"properties": {
										"eq": {
											"type": "string"
										}
									},
									"required": ["eq"]
								},
								{
									"properties": {
										"neq": {
											"type": "string"
										}
									},
									"required": ["neq"]
								}
							]
						}
					]
				},
				"mapping": {
					"type": "object"
				},
				"name": {
					"type": "string"
				},
				"options": {
					"type": "array",
					"readonly": true
				},
				"table": {
					"type": "object",
					"properties": {
						"category": {
							"type": "string"
						},
						"subcategory": {
							"type": "string"
						},
						"defaultValue": {
							"type": "object",
							"properties": {
								"summary": {
									"type": "string"
								},
								"detail": {
									"type": "string"
								}
							}
						},
						"disable": {
							"type": "boolean"
						},
						"type": {
							"type": "object",
							"properties": {
								"summary": {
									"type": "string"
								},
								"detail": {
									"type": "string"
								}
							}
						}
					},
					"additionalProperties": true
				},
				"type": {}
			},
			"additionalProperties": false
		},
		"control": {
			"oneOf": [
				{
					"$ref": "#/definitions/controlTypes"
				},
				{
					"type": "boolean",
					"enum": [false]
				},
				{
					"type": "object",
					"properties": {
						"type": {
							"$ref": "#/definitions/controlTypes"
						},
						"disable": {
							"type": "boolean"
						}
					},
					"required": ["type"],
					"allOf": [
						{
							"if": {
								"properties": {
									"type": { "const": "color" }
								},
								"then": {
									"properties": {
										"presetColors": { "type": "array", "items": { "type": "string" } }
									}
								}
							}
						},
						{
							"if": {
								"properties": {
									"type": { "const": "file" }
								},
								"then": {
									"properties": {
										"accept": { "type": "string" }
									}
								}
							}
						},
						{
							"if": {
								"properties": {
									"type": { "anyOf": [ { "const": "inline-check" }, { "const": "radio" }, { "const": "inline-radio" }, { "const": "select" }, { "const": "multi-select" } ] }
								},
								"then": {
									"properties": {
										"labels": { "type": "object", "patternProperties": { "^.*$": { "type": "string" } } }
									}
								}
							}
						},
						{
							"if": {
								"properties": {
									"type": { "anyOf": [ { "const": "range" }, { "const": "number" } ] }
								},
								"then": {
									"properties": {
										"max": { "type": "number" },
										"min": { "type": "number" },
										"step": { "type": "number" }
									}
								}
							}
						}
					]
				}
			]
		},
		"controlTypes": {
			"type": "string",
			"enum": ["color", "date", "boolean", "number", "text", "object", "check", "inline-check", "radio", "inline-radio", "select", "multi-select", "file", "range"]
		}
	}
}

=== adobe/spectrum-css/components/opacitycheckerboard/dist/metadata.json
{
  "sourceFile": "index.css",
  "selectors": [".spectrum-OpacityCheckerboard"],
  "modifiers": {
    "mod-opacity-checkerboard-light": {
      "value": "var(--spectrum-white)",
      "description": "Used by `.spectrum-OpacityCheckerboard`. <br/>Defaults to `var(--spectrum-opacity-checkerboard-square-light)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-opacity-checkerboard-dark": {
      "value": "var(--spectrum-gray-800)",
      "description": "Used by `.spectrum-OpacityCheckerboard`. <br/>Defaults to `var(--spectrum-opacity-checkerboard-square-dark)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-opacity-checkerboard-position": {
      "description": "Used by `.spectrum-OpacityCheckerboard`.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-opacity-checkerboard-size": {
      "value": "8px",
      "description": "Used by `.spectrum-OpacityCheckerboard`. <br/>Defaults to `var(--spectrum-opacity-checkerboard-square-size)`, if not set.",
      "control": "text",
      "category": "Modifier"
    }
  },
  "component": {
    "spectrum-opacity-checkerboard-square-light": {
      "value": "var(--spectrum-white)",
      "description": "Used by `.spectrum-OpacityCheckerboard`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-opacity-checkerboard-square-dark": {
      "value": "var(--spectrum-gray-800)",
      "description": "Used by `.spectrum-OpacityCheckerboard`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-opacity-checkerboard-square-size": {
      "value": "8px",
      "description": "Used by `.spectrum-OpacityCheckerboard`.",
      "control": "text",
      "category": "Component"
    }
  },
  "global": {},
  "system-theme": {},
  "passthroughs": {},
  "high-contrast": {}
}

=== adobe/spectrum-css/components/well/dist/metadata.json
{
  "sourceFile": "index.css",
  "selectors": [".spectrum-Well"],
  "modifiers": {
    "mod-well-min-width": {
      "description": "Used by `.spectrum-Well`. <br/>Defaults to `var(--spectrum-well-min-width)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-well-padding": {
      "description": "Used by `.spectrum-Well`. <br/>Defaults to `var(--spectrum-well-padding)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-well-margin-top": {
      "description": "Used by `.spectrum-Well`. <br/>Defaults to `var(--spectrum-well-margin-top)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-well-border-width": {
      "description": "Used by `.spectrum-Well`. <br/>Defaults to `var(--spectrum-well-border-width)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-well-border-radius": {
      "description": "Used by `.spectrum-Well`. <br/>Defaults to `var(--spectrum-well-border-radius)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-well-background-color": {
      "description": "Used by `.spectrum-Well`. <br/>Defaults to `var(--spectrum-well-background-color)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-well-border-color": {
      "description": "Used by `.spectrum-Well`. <br/>Defaults to `var(--spectrum-well-border-color)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-well-content-color": {
      "description": "Used by `.spectrum-Well`. <br/>Defaults to `var(--spectrum-well-content-color)`, if not set.",
      "control": "color",
      "category": "Modifier"
    }
  },
  "component": {
    "spectrum-well-border-width": {
      "value": "1px",
      "description": "Defined in `.spectrum-Well`. <br/>Used by `.spectrum-Well`. <br/>Defaults to `var(--spectrum-border-width-100)`, if not set.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-well-content-color": {
      "value": "var(--spectrum-gray-800)",
      "description": "Defined in `.spectrum-Well`. <br/>Used by `.spectrum-Well`. <br/>Defaults to `var(--spectrum-body-color)`, if not set.",
      "control": "color",
      "category": "Component"
    },
    "spectrum-well-background-color": {
      "value": "rgb(var(--spectrum-gray-800-rgb), 0.02)",
      "description": "Defined in `.spectrum-Well`. <br/>Used by `.spectrum-Well`. <br/>Defaults to `rgb(var(--spectrum-gray-800-rgb), 0.02)`, if not set.",
      "control": "color",
      "category": "Component"
    },
    "spectrum-well-min-width": {
      "description": "Used by `.spectrum-Well`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-well-padding": {
      "description": "Used by `.spectrum-Well`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-well-margin-top": {
      "description": "Used by `.spectrum-Well`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-well-border-radius": {
      "description": "Used by `.spectrum-Well`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-well-border-color": {
      "value": "var(--system-well-border-color)",
      "description": "Defined in `.spectrum-Well`. <br/>Used by `.spectrum-Well`. <br/>Defaults to `var(--system-well-border-color)`, if not set.",
      "control": "color",
      "category": "Component"
    }
  },
  "global": {
    "spectrum-gray-1000-rgb": {
      "description": "Used by `--system-well-border-color`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-border-width-100": {
      "value": "1px",
      "description": "Used by `--spectrum-well-border-width`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-body-color": {
      "value": "var(--spectrum-gray-800)",
      "description": "Used by `--spectrum-well-content-color`.",
      "control": "color",
      "category": "Global"
    },
    "spectrum-gray-800-rgb": {
      "description": "Used by `--spectrum-well-background-color`.",
      "control": "text",
      "category": "Global"
    }
  },
  "system-theme": {
    "system-well-border-color": {
      "value": "rgb(var(--spectrum-gray-1000-rgb), 0.05)",
      "description": "Defined in `.spectrum`. <br/>Used by `--spectrum-well-border-color`. <br/>Defaults to `rgb(var(--spectrum-gray-1000-rgb), 0.05)`, if not set.",
      "control": "color"
    }
  },
  "passthroughs": {},
  "high-contrast": {}
}

=== adobe/spectrum-css/components/divider/dist/metadata.json
{
  "sourceFile": "index.css",
  "selectors": [
    ".spectrum-Divider",
    ".spectrum-Divider--sizeL",
    ".spectrum-Divider--sizeS",
    ".spectrum-Divider--staticBlack",
    ".spectrum-Divider--staticBlack.spectrum-Divider--sizeL",
    ".spectrum-Divider--staticBlack.spectrum-Divider--sizeS",
    ".spectrum-Divider--staticWhite",
    ".spectrum-Divider--staticWhite.spectrum-Divider--sizeL",
    ".spectrum-Divider--staticWhite.spectrum-Divider--sizeS",
    ".spectrum-Divider--vertical"
  ],
  "modifiers": {
    "mod-divider-background-color": {
      "value": "var(--spectrum-divider-background-color)",
      "description": "Defined in `.spectrum-Divider--staticWhite`, `.spectrum-Divider--staticWhite.spectrum-Divider--sizeS`, `.spectrum-Divider--staticWhite.spectrum-Divider--sizeL`, `.spectrum-Divider--staticBlack`, `.spectrum-Divider--staticBlack.spectrum-Divider--sizeS`, `.spectrum-Divider--staticBlack.spectrum-Divider--sizeL`. <br/>Used by `.spectrum-Divider`. <br/>Defaults to `var(--spectrum-divider-background-color)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-divider-background-color-medium-static-white": {
      "value": "var(--spectrum-divider-background-color-static-white)",
      "description": "Used by `--mod-divider-background-color`. <br/>Defaults to `var(--spectrum-divider-background-color-static-white)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-divider-background-color-small-static-white": {
      "value": "var(--spectrum-divider-background-color-static-white)",
      "description": "Used by `--mod-divider-background-color`. <br/>Defaults to `var(--spectrum-divider-background-color-static-white)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-divider-background-color-large-static-white": {
      "value": "light-dark(rgba(255, 255, 255, 0.85), rgba(255, 255, 255, 0.85))",
      "description": "Used by `--mod-divider-background-color`. <br/>Defaults to `var(--spectrum-transparent-white-800)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-divider-background-color-medium-static-black": {
      "value": "var(--spectrum-divider-background-color-static-black)",
      "description": "Used by `--mod-divider-background-color`. <br/>Defaults to `var(--spectrum-divider-background-color-static-black)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-divider-background-color-small-static-black": {
      "value": "var(--spectrum-divider-background-color-static-black)",
      "description": "Used by `--mod-divider-background-color`. <br/>Defaults to `var(--spectrum-divider-background-color-static-black)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-divider-background-color-large-static-black": {
      "value": "light-dark(rgba(0, 0, 0, 0.84), rgba(0, 0, 0, 0.84))",
      "description": "Used by `--mod-divider-background-color`. <br/>Defaults to `var(--spectrum-transparent-black-800)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-divider-thickness": {
      "value": "var(--spectrum-divider-thickness)",
      "description": "Used by `.spectrum-Divider`, `.spectrum-Divider--vertical`. <br/>Defaults to `var(--spectrum-divider-thickness)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-divider-vertical-height": {
      "description": "Used by `.spectrum-Divider--vertical`.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-divider-vertical-margin": {
      "description": "Used by `.spectrum-Divider--vertical`.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-divider-vertical-align": {
      "description": "Used by `.spectrum-Divider--vertical`.",
      "control": "text",
      "category": "Modifier"
    }
  },
  "component": {
    "spectrum-divider-thickness": {
      "description": "Defined in `.spectrum-Divider`, `.spectrum-Divider--sizeS`, `.spectrum-Divider--sizeL`. <br/>Used by `.spectrum-Divider`, `.spectrum-Divider--vertical`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-divider-thickness-medium": {
      "value": "2px",
      "description": "Used by `--spectrum-divider-thickness`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-divider-thickness-small": {
      "value": "1px",
      "description": "Used by `--spectrum-divider-thickness`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-divider-thickness-large": {
      "value": "4px",
      "description": "Used by `--spectrum-divider-thickness`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-divider-background-color": {
      "description": "Defined in `.spectrum-Divider--sizeL`, `.spectrum-Divider`. <br/>Used by `.spectrum-Divider`.",
      "control": "color",
      "category": "Component"
    },
    "spectrum-divider-background-color-static-white": {
      "description": "Defined in `.spectrum-Divider`. <br/>Used by `--mod-divider-background-color`.",
      "control": "color",
      "category": "Component"
    },
    "spectrum-divider-background-color-static-black": {
      "description": "Defined in `.spectrum-Divider`. <br/>Used by `--mod-divider-background-color`.",
      "control": "color",
      "category": "Component"
    }
  },
  "global": {
    "spectrum-gray-200": {
      "value": "light-dark(rgb(225, 225, 225), rgb(50, 50, 50))",
      "description": "Used by `--system-divider-background-color`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-transparent-white-200": {
      "value": "light-dark(rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.14))",
      "description": "Used by `--system-divider-background-color-static-white`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-transparent-black-200": {
      "value": "light-dark(rgba(0, 0, 0, 0.12), rgba(0, 0, 0, 0.12))",
      "description": "Used by `--system-divider-background-color-static-black`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-gray-800": {
      "value": "light-dark(rgb(41, 41, 41), rgb(219, 219, 219))",
      "description": "Used by `--spectrum-divider-background-color`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-transparent-white-800": {
      "value": "light-dark(rgba(255, 255, 255, 0.85), rgba(255, 255, 255, 0.85))",
      "description": "Used by `--mod-divider-background-color`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-transparent-black-800": {
      "value": "light-dark(rgba(0, 0, 0, 0.84), rgba(0, 0, 0, 0.84))",
      "description": "Used by `--mod-divider-background-color`.",
      "control": "text",
      "category": "Global"
    }
  },
  "system-theme": {
    "system-divider-background-color": {
      "description": "Defined in `.spectrum`. <br/>Used by `--spectrum-divider-background-color`.",
      "control": "color"
    },
    "system-divider-background-color-static-white": {
      "description": "Defined in `.spectrum`. <br/>Used by `--spectrum-divider-background-color-static-white`.",
      "control": "color"
    },
    "system-divider-background-color-static-black": {
      "description": "Defined in `.spectrum`. <br/>Used by `--spectrum-divider-background-color-static-black`.",
      "control": "color"
    }
  },
  "passthroughs": {},
  "high-contrast": {
    "highcontrast-divider-background-color": {
      "value": "var(--mod-divider-background-color, var(--spectrum-divider-background-color))",
      "description": "Defined in `.spectrum-Divider`. <br/>Used by `.spectrum-Divider`. <br/>Defaults to `var(--mod-divider-background-color, var(--spectrum-divider-background-color))`, if not set.",
      "control": "color"
    }
  }
}

=== adobe/spectrum-css/components/tray/dist/metadata.json
{
  "sourceFile": "index.css",
  "selectors": [
    ".spectrum-Tray",
    ".spectrum-Tray .spectrum-Dialog",
    ".spectrum-Tray-wrapper",
    ".spectrum-Tray.is-open"
  ],
  "modifiers": {
    "mod-tray-max-inline-size": {
      "description": "Used by `--spectrum-tray-max-inline-size`.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-tray-spacing-edge-to-tray-safe-zone": {
      "description": "Used by `--spectrum-tray-spacing-edge-to-tray-safe-zone`.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-tray-entry-animation-delay": {
      "description": "Used by `--spectrum-tray-entry-animation-delay`.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-tray-entry-animation-duration": {
      "value": "var(--spectrum-animation-duration-500)",
      "description": "Used by `--spectrum-tray-entry-animation-duration`. <br/>Defaults to `var(--spectrum-animation-duration-500)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-tray-exit-animation-delay": {
      "description": "Used by `--spectrum-tray-exit-animation-delay`.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-tray-exit-animation-duration": {
      "value": "var(--spectrum-animation-duration-100)",
      "description": "Used by `--spectrum-tray-exit-animation-duration`. <br/>Defaults to `var(--spectrum-animation-duration-100)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-tray-corner-radius": {
      "value": "8px",
      "description": "Used by `--spectrum-tray-corner-radius`. <br/>Defaults to `var(--spectrum-corner-radius-100)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-tray-background-color": {
      "value": "var(--spectrum-gray-75)",
      "description": "Used by `--spectrum-tray-background-color`. <br/>Defaults to `var(--spectrum-background-layer-2-color)`, if not set.",
      "control": "color",
      "category": "Modifier"
    },
    "mod-tray-top-to-content-area": {
      "value": "4px",
      "description": "Used by `.spectrum-Tray`. <br/>Defaults to `var(--spectrum-tray-top-to-content-area)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-tray-bottom-to-content-area": {
      "value": "4px",
      "description": "Used by `.spectrum-Tray`. <br/>Defaults to `var(--spectrum-tray-top-to-content-area)`, if not set.",
      "control": "text",
      "category": "Modifier"
    },
    "mod-tray-corner-radius-portrait": {
      "description": "Used by `.spectrum-Tray`.",
      "control": "text",
      "category": "Modifier"
    }
  },
  "component": {
    "spectrum-tray-max-inline-size": {
      "description": "Defined in `.spectrum-Tray`. <br/>Used by `.spectrum-Tray`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-tray-spacing-edge-to-tray-safe-zone": {
      "description": "Defined in `.spectrum-Tray`. <br/>Used by `.spectrum-Tray`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-tray-entry-animation-delay": {
      "description": "Defined in `.spectrum-Tray`. <br/>Used by `.spectrum-Tray.is-open`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-tray-entry-animation-duration": {
      "description": "Defined in `.spectrum-Tray`. <br/>Used by `.spectrum-Tray.is-open`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-tray-exit-animation-delay": {
      "description": "Defined in `.spectrum-Tray`. <br/>Used by `.spectrum-Tray`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-tray-exit-animation-duration": {
      "description": "Defined in `.spectrum-Tray`. <br/>Used by `.spectrum-Tray`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-tray-corner-radius": {
      "description": "Defined in `.spectrum-Tray`. <br/>Used by `.spectrum-Tray`.",
      "control": "text",
      "category": "Component"
    },
    "spectrum-tray-background-color": {
      "description": "Defined in `.spectrum-Tray`. <br/>Used by `.spectrum-Tray`.",
      "control": "color",
      "category": "Component"
    },
    "spectrum-tray-top-to-content-area": {
      "value": "4px",
      "description": "Used by `.spectrum-Tray`.",
      "control": "text",
      "category": "Component"
    }
  },
  "global": {
    "spectrum-animation-duration-500": {
      "description": "Used by `--spectrum-tray-entry-animation-duration`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-animation-duration-100": {
      "description": "Used by `--spectrum-tray-exit-animation-duration`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-corner-radius-100": {
      "value": "8px",
      "description": "Used by `--spectrum-tray-corner-radius`.",
      "control": "text",
      "category": "Global"
    },
    "spectrum-background-layer-2-color": {
      "value": "var(--spectrum-gray-75)",
      "description": "Used by `--spectrum-tray-background-color`.",
      "control": "color",
      "category": "Global"
    }
  },
  "system-theme": {},
  "passthroughs": {
    "mod-modal-max-width": {
      "category": "Passthrough"
    }
  },
  "high-contrast": {
    "highcontrast-tray-background-color": {
      "value": "var(--mod-tray-background-color, var(--spectrum-background-layer-2-color))",
      "description": "Defined in `.spectrum-Tray`. <br/>Used by `--spectrum-tray-background-color`. <br/>Defaults to `var(--mod-tray-background-color, var(--spectrum-background-layer-2-color))`, if not set.",
      "control": "color"
    }
  }
}
